# Allows restoring GPU memory after suspend
options nvidia NVreg_PreserveVideoMemoryAllocations=1

# For some reason, default 0x03 setting causes GPU to not stay asleep
# options nvidia NVreg_DynamicPowerManagement=0x02
# options nvidia NVreg_DynamicPowerManagementVideoMemoryThreshold=0

# For detailed logs
# options nvidia NVreg_ResmanDebugLevel=1
